name 'policyfiles_from_env_files'
maintainer 'Collin McNeese'
maintainer_email 'collin@mydevsandbox.com'
license 'Apache-2.0'
description 'Installs/Configures policyfiles_from_env_files'
version '0.1.0'
chef_version '>= 15.0'
